In [14]:
import nibabel as nib
import numpy as np

import os
import imageio

In [19]:
im = imageio.imread(r'D:\Segthordataset\train\Patient_02_png\GT.nii.gz\Patient0_02141.png')
im.dtype
np.unique(im, return_counts=True)

d:\anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  """Entry point for launching an IPython kernel.


(Array([  0, 252, 254, 255], dtype=uint8),
 array([250763,    568,  10638,    175], dtype=int64))

In [3]:
im.shape

(512, 512)

In [4]:
np.unique(im, return_counts=True)

(Array([  0, 252, 253, 255], dtype=uint8),
 array([259884,   1485,    599,    176], dtype=int64))

In [6]:
im_1 = imageio.imread(r'D:\Segthordataset\train\Patient_01_png\Patient_01.nii.gz\Patient0_01121.png')
im_1.dtype

d:\anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  """Entry point for launching an IPython kernel.


dtype('uint8')

In [7]:
im_1.shape

(512, 512)

In [8]:
np.unique(im_1, return_counts=True)

(Array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

### Test image

In [2]:
im_img = imageio.imread(r'D:\TransUnet\dataset\build\train\images\22678915_15_28.png')
im_img.dtype

d:\anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  """Entry point for launching an IPython kernel.


dtype('uint8')

In [3]:
im_img.shape

(256, 256, 3)

In [6]:
im_ = im_img.transpose(2,0,1)

In [7]:
im_.shape

(3, 256, 256)

In [4]:
im_mask = imageio.imread(r'D:\TransUnet\dataset\build\train\labels\22678915_15_28.png')
im_mask.dtype

d:\anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  """Entry point for launching an IPython kernel.


dtype('uint8')

In [5]:
im_mask.shape

(256, 256)